name: tana_kala
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  easy_search_bar: ^2.5.0
  flutter_svg: ^2.0.6
  smooth_page_indicator: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  fonts:
    - family: icomoon
      fonts:
        - asset: icons/icomoon.ttf
    - family: Peyda
      fonts:
        - asset: fonts/Peyda-Regular.ttf
          weight: 500
        - asset: fonts/Peyda-Bold.ttf
          weight: 700
        - asset: fonts/Peyda-ExtraBold.ttf
          weight: 800
        - asset: fonts/Peyda-SemiBold.ttf
          weight: 700
        - asset: fonts/Peyda-Medium.ttf
          weight: 600
        - asset: fonts/peyda-extralight.ttf
          weight: 400
        - asset: fonts/Peyda-Black.ttf
          weight: 900
        - asset: fonts/peyda-light.ttf
          weight: 300
        - asset: fonts/Peyda-Thin.ttf
          weight: 100
  uses-material-design: true
